# -*- coding: utf-8 -*-
"""eeg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEdmkIsQKKk7FTNioCEbBSbI-Wt2_vkV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import signal
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.metrics import confusion_matrix, classification_report
import random

data = pd.read_csv('/content/emotionss.csv')

data.head(22)

label_mapping = {'NEGATIVE': 0, 'NEUTRAL': 1, 'POSITIVE': 2}
data['label'] = data['label'].map(label_mapping)

"""Step 2: Emotion Distribution

The code creates a pie chart to visualize the distribution of emotions in the dataset. It helps understand how emotions are representation in the data
"""

emotion_counts = data['label'].value_counts()

emotional_labels = {0: 'NEGATIVE', 1: 'NEUTRAL', 2: 'POSITIVE'}


emotion_labels = [emotional_labels[label] for label in emotion_counts.index]


plt.figure(figsize=(8, 8))
plt.pie(emotion_counts, labels=emotion_labels, autopct='%1.1f%%', startangle=140, colors=['red', 'yellow', 'green'])
plt.title("Distribution of Emotions (0: NEGATIVE, 1: NEUTRAL, 2: POSITIVE)")
plt.axis('equal')  # Equal aspect ratio ensures that the pie is drawn as a circle.

plt.show()

"""Step 3: Time-Series Visualization

The code diaplays a time-series plot of EEG data from a signal sample. It shows how the EEG signal varies over time
"""

sample = data.loc[0, 'fft_0_b':'fft_749_b']
plt.figure(figsize=(16, 10))
plt.plot(range(len(sample)), sample)
plt.title("EEG Time-Series Data")
plt.xlabel("Time")
plt.ylabel("Amplitude")
plt.show()

"""Step 4: Spectral Analysis

The code performs spectral analysis on the EEG data, providing insights into frequency components. It displays a power spectral density plot
"""

sampling_rate = 256


frequencies, power_density = signal.welch(sample.values, fs=sampling_rate)
plt.figure(figsize=(10, 6))
plt.semilogy(frequencies, power_density)
plt.title("Power Spectral Density")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Power/Frequency")
plt.grid()
plt.show()

"""Step 5: Correlation Heatmap

A heatmap is generated to show correlation between different features in the EEG data. This helps identify patterns and relationships among features.
"""

correlation_matrix = data.drop('label', axis=1).corr()
plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, cmap='coolwarm', vmin=-1, vmax=1)
plt.title("Correlation Heatmap")
plt.show()

"""Step 6: t-SNE Visualization

t-SNE (t-distributed Stochastic Neighbor Embedding) is used for dimensionality reduction and visualize the data's separability based on emotions.
"""

from sklearn.manifold import TSNE
# Drop rows with NaN values
data_cleaned = data.dropna()
tsne = TSNE(n_components=2, random_state=42)
tsne_results = tsne.fit_transform(data_cleaned.drop('label', axis=1))
tsne_df = pd.DataFrame(tsne_results, columns=['Dimension 1', 'Dimension 2'])
tsne_df['label'] = data_cleaned['label']
plt.figure(figsize=(10, 8))
sns.scatterplot(x='Dimension 1', y='Dimension 2', hue='label', data=tsne_df, palette='viridis')
plt.title("t-SNE Visualization")
plt.show()

"""Step 7: Feature Significance Analysis

The code assesses the significance of different features in predictiong emotins. It calculates the number of significant and non-significant features for each emotion.
"""

emotions = data['label'].unique()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind


significant_color = 'green'
non_significant_color = 'red'

# Drop rows with NaN values to handle missing data
data_cleaned = data.dropna()

# Get unique emotions from the cleaned data
emotions = data_cleaned['label'].unique()

num_features = {emotion: {'significant': 0, 'non-significant': 0} for emotion in emotions}


for emotion in emotions:
    subset = data_cleaned[data_cleaned['label'] == emotion]
    for feature in data_cleaned.columns[:-1]:
        # Ensure there are enough samples and no NaNs in the feature data for the t-test
        if len(subset[feature].dropna()) > 1 and len(data_cleaned[feature].dropna()) > 1:
             _, p_value = ttest_ind(subset[feature].dropna(), data_cleaned[feature].dropna())
             if p_value < 0.05:
                 num_features[emotion]['significant'] += 1
             else:
                 num_features[emotion]['non-significant'] += 1
        else:
            # If not enough samples or NaNs, consider it non-significant for this analysis
             num_features[emotion]['non-significant'] += 1


emotion_labels = list(num_features.keys())
significant_counts = [num_features[emotion]['significant'] for emotion in emotion_labels]
non_significant_counts = [num_features[emotion]['non-significant'] for emotion in emotion_labels]


plt.figure(figsize=(12, 6))
bar_width = 0.35
index = np.arange(len(emotion_labels))

plt.bar(index, significant_counts, bar_width, label='Significant', color=significant_color)
plt.bar(index + bar_width, non_significant_counts, bar_width, label='Non-Significant', color=non_significant_color)


plt.xlabel('Emotion (0: Negative, 1: Neutral, 2: Positive)')
plt.ylabel('Number of Features')
plt.title('Significant and Non-Significant Features by Emotion')
plt.xticks(index + bar_width / 2, emotion_labels)
plt.legend()


for i, (significant_count, non_significant_count) in enumerate(zip(significant_counts, non_significant_counts)):
    plt.text(i, significant_count + non_significant_count + 1, f'S: {significant_count}\nNS: {non_significant_count}', ha='center', va='bottom', fontsize=12)

plt.xticks(rotation=45)
plt.tight_layout()


plt.figure(figsize=(8, 4))
plt.text(0.5, 0.5, 'Significant Features: These features show\nstatistically significant differences\nacross different emotions.',
         ha='center', va='center', fontsize=12, bbox=dict(facecolor='lightgray', edgecolor='gray', boxstyle='round,pad=0.5'))
plt.axis('off')

plt.show()

"""Step 8: Advanced Preprocessing

The EEG data is normalized using z-score normalization. Then, the data is split into trainig and testing sets for machine learning.
"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data.iloc[:, :-1] = scaler.fit_transform(data.iloc[:, :-1])

X = data.drop('label', axis=1)
y = data['label']
# Drop rows with NaN values from both X and y
data_cleaned = data.dropna()
X = data_cleaned.drop('label', axis=1)
y = data_cleaned['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

"""Step 9: Neural Network Model

An advanced neural network model is build and trained using TensorFlow. This model is designed to predict emotions based on EEG features.
"""

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train, validation_split=0.2, epochs=70, batch_size=32, verbose=2)

"""Step 10: Model Evaluation

The code evaluates the models's performance using metrics like accuracy,and it generates a confusion matrix to visualize the model's predictions.
"""

model_acc = model.evaluate(X_test, y_test, verbose=0)[1]
print("Test Accuracy: {:.3f}%".format(model_acc * 100))

y_pred = np.argmax(model.predict(X_test), axis=-1)

cm = confusion_matrix(y_test, y_pred)
clr = classification_report(y_test, y_pred, target_names=label_mapping.keys())

plt.figure(figsize=(8, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False, xticklabels=label_mapping.keys(), yticklabels=label_mapping.keys())
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:\n", clr)

"""Step 11: Signal Visualization

A random sample from the test data is selected, and the model predicts the associated emotion. The EEG signals for this sample are visualized for all available channels
"""

# Install the required modules
!pip install tensorflow

# Import the required modules
import tensorflow as tf

# Define a custom Keras layer to wrap tf.expand_dims
class ExpandDimsLayer(tf.keras.layers.Layer):
    def __init__(self, axis, **kwargs):
        super(ExpandDimsLayer, self).__init__(**kwargs)
        self.axis = axis

    def call(self, inputs):
        return tf.expand_dims(inputs, axis=self.axis)

    def get_config(self):
        config = super(ExpandDimsLayer, self).get_config()
        config.update({'axis': self.axis})
        return config

# Define the input layer
inputs = tf.keras.Input(shape=(X_train.shape[1],)) # Use the actual number of features from X_train

# Expand the dimension of the input using the custom layer
expand_dims = ExpandDimsLayer(axis=2)(inputs)

# Add a GRU layer
gru = tf.keras.layers.GRU(256, return_sequences=True)(expand_dims)

# Flatten the output of the GRU layer
flatten = tf.keras.layers.Flatten()(gru)

# Add a Dense layer with 3 outputs and a softmax activation
outputs = tf.keras.layers.Dense(3, activation='softmax')(flatten)

# Create the model
model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Print the model summary
model.summary()

import tensorflow as tf

# Define a custom Keras layer to wrap tf.expand_dims
class ExpandDimsLayer(tf.keras.layers.Layer):
    def __init__(self, axis, **kwargs):
        super(ExpandDimsLayer, self).__init__(**kwargs)
        self.axis = axis

    def call(self, inputs):
        return tf.expand_dims(inputs, axis=self.axis)

    def get_config(self):
        config = super(ExpandDimsLayer, self).get_config()
        config.update({'axis': self.axis})
        return config

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

label_mapping = {0: 'NEGATIVE', 1: 'NEUTRAL', 2: 'POSITIVE'}

import random

emotion_labels = {0: 'NEGATIVE', 1: 'NEUTRAL', 2: 'POSITIVE'}


for i in range(6, 8):
    random_index = random.randint(0, len(X_test) - 1)
    sample_input = X_test.iloc[random_index].values.reshape(1, -1)
    true_label = y_test.iloc[random_index]
    true_emotion = emotion_labels.get(true_label, 'Unknown')  # Use .get() to avoid KeyError


    predicted_emotion = model.predict(sample_input)
    predicted_label = emotion_labels[np.argmax(predicted_emotion)]


    print(f"Sample {i}: Real Emotion Label: {true_emotion}, Predicted Emotion Label: {predicted_label}")

plt.figure(figsize=(25,7))
plt.title("Data distribution of Emotions")
plt.style.use('fivethirtyeight')
sns.countplot(x='label', data=data)
plt.show()