# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoTevt0rrrWqHWQ75o8hWCCmF4lJGd5i
"""

# Import Required Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("/content/heart.csv")

# Display first 5 rows
data.head()

# Dataset information
data.info()

#describe function
data.describe()

# Check missing values
data.isnull().sum()

# X = input features
X = data.drop("target", axis=1)

# y = output
y = data["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:",round(accuracy * 100, 2), "%")

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

new_patient = np.array([[52,1,0,125,212,0,1,168,0,1.0,2,2,3]])

prediction = model.predict(new_patient)

if prediction[0] == 1:
    print("Patient is likely to have Heart Disease")
else:
    print("Patient is NOT likely to have Heart Disease")

